### ISSUE TITLE
Error in columns.lua with Pandoc 2.6

### ISSUE THREAD

**Issue by fsoedjede** [jdutant/columns#7]
Hello,

Thanks for this filter which seems complete.

While testing with the README.md and running the command `make`, pandoc throws this error :

```shell
$ make
pandoc --lua-filter columns.lua --standalone --output expected.html README.md
Error running filter columns.lua:
attempt to index a nil value
stack traceback:
        [C]: in metamethod '__index'
        columns.lua:393: in upvalue 'convert_explicit_columbreaks'
        columns.lua:583: in function <columns.lua:578>
        (...tail calls...)
make: *** [expected.html] Error 83
```

I think there is a missing condition at the lines https://github.com/jdutant/columns/blob/master/columns.lua#L393-L394

Here is my proposal:
```diff
# https://github.com/jdutant/columns/blob/master/columns.lua#L393-L394
-  if elem.content[#elem.content] and elem.content[#elem.content].classes
-    and elem.content[#elem.content].classes:includes('column') then
+    if elem.content[#elem.content]
+    and elem.content[#elem.content].t == 'Div'
+    and elem.content[#elem.content].classes
+    and elem.content[#elem.content].classes:includes('column') then
```

The main addition here is that we now check if the element is a `Div`. After adding that, everything works fine

Can I submit a pull request with that change?

Thanks

**Comment by jdutant** [comment]
Hey, thanks a lot - and sorry for the delayed reply. You're right! Please submit a PR and I'll merge.
