### ISSUE TITLE
citeproc bibliography column control

### ISSUE THREAD

**Issue by t3dr0** [jdutant/columns#9]
[removed]

**Comment by jdutant** [comment]
The original question was whether columns could be applied within the citeproc bibliography. It cannot without a filter, because Pandoc places the citeproc bibliography in a `<div>...</div>` container. As explained in the docs for this repo, Div elements aren't broken up in HTML fluid columns. 

> Beware though that Divs elements within a column are counted as unbreakable blocks in most browsers. For instance, the following places a Div with classes ".only-in-format .html" within a fluid multiple columns ....
